import { Router, type IRouter } from "express";

import healthRouter from "./health.js";
import authRouter from "./auth.js";
import menuRouter from "./menu.js";
import ordersStatusRouter from "./orders-status.js";
import ordersRouter from "./orders.js";
import tablesRouter from "./tables.js";
import inventoryCostSnapshotRepairsRouter from "./inventory-cost-snapshot-repairs.js";
import inventoryRouter from "./inventory.js";
import cashierShiftReportsGuardRouter from "./cashier-shift-reports-guard.js";
import cashierShiftReportsRouter from "./cashier-shift-reports.js";
import cashierShiftReportsReconciliationRouter from "./cashier-shift-reports-reconciliation.js";
import cashierShiftSyncAttemptsRouter from "./cashier-shift-sync-attempts.js";
import cashflowRouter from "./cashflow.js";
import financialReportsGuardRouter from "./financial-reports-guard.js";
import financialReportsRepairAuditRouter from "./financial-reports-repair-audit.js";
import reportsRouter from "./financial-reports.js";
import salesAnalyticsRouter from "./sales-analytics.js";
import shiftsRouter from "./shifts.js";
import paymentsRouter from "./payments.js";
import invoiceStatusRouter from "./invoice-status.js";
import invoiceSummaryRouter from "./invoice-summary.js";
import invoiceFollowUpAnalyticsRouter from "./invoice-follow-up-analytics.js";
import invoiceFollowUpsRouter from "./invoice-follow-ups.js";
import invoiceFollowUpRemindersRouter from "./invoice-follow-up-reminders.js";
import invoicesRouter from "./invoices.js";
import restaurantRouter from "./restaurant.js";
import restaurantPaymentReversalRouter from "./restaurant-payment-reversal.js";
import restaurantSecurityRouter from "./restaurant-security.js";
import teamManagementRouter from "./team-management.js";
import internalMonitoringRouter from "./internal-monitoring.js";
import retailRouter from "./retail.js";
import rawMaterialApiRouter from "./raw-material.js";
import rawMaterialProcessingRouter from "./raw-material-processing.js";
import rawMaterialPensRouter from "./raw-material-pens.js";
import rawMaterialStockMovementsRouter from "./raw-material-stock-movements.js";
import rawMaterialSummaryRouter from "./raw-material-summary.js";
import rawMaterialPreviewRouter from "./raw-material-preview.js";
import rawMaterialStatusRouter from "./raw-material-status.js";
import serviceBusinessWorkflowRouter from "./service-business-workflow.js";
import serviceBusinessPreviewRouter from "./service-business-preview.js";
import serviceBusinessStatusRouter from "./service-business-status.js";
import serviceBusinessReversalRouter from "./service-business-reversal.js";
import serviceBusinessRouter from "./service-business.js";
import miscBusinessRouter from "./misc-business.js";
import miscRouter from "./misc.js";
import eventsRouter from "./events.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(menuRouter);
router.use(ordersStatusRouter);
router.use(ordersRouter);
router.use(tablesRouter);
router.use(inventoryCostSnapshotRepairsRouter);
router.use(inventoryRouter);
router.use(cashierShiftReportsGuardRouter);
router.use(cashierShiftReportsRouter);
router.use(cashierShiftReportsReconciliationRouter);
router.use(cashierShiftSyncAttemptsRouter);
router.use(cashflowRouter);
router.use(financialReportsGuardRouter);
router.use(financialReportsRepairAuditRouter);
router.use(reportsRouter);
router.use(salesAnalyticsRouter);
router.use(shiftsRouter);
router.use(paymentsRouter);
router.use(invoiceStatusRouter);
router.use(invoiceSummaryRouter);
router.use(invoiceFollowUpAnalyticsRouter);
router.use(invoiceFollowUpsRouter);
router.use(invoiceFollowUpRemindersRouter);
router.use(invoicesRouter);
router.use(restaurantRouter);
router.use(restaurantPaymentReversalRouter);
router.use(restaurantSecurityRouter);
router.use(teamManagementRouter);
router.use(internalMonitoringRouter);
router.use(retailRouter);
router.use(rawMaterialApiRouter);
router.use(rawMaterialProcessingRouter);
router.use(rawMaterialPensRouter);
router.use(rawMaterialStockMovementsRouter);
router.use(rawMaterialSummaryRouter);
router.use(rawMaterialPreviewRouter);
router.use(rawMaterialStatusRouter);
router.use(serviceBusinessWorkflowRouter);
router.use(serviceBusinessPreviewRouter);
router.use(serviceBusinessStatusRouter);
router.use(serviceBusinessReversalRouter);
router.use(serviceBusinessRouter);
router.use(miscBusinessRouter);
router.use(miscRouter);
router.use(eventsRouter);

export default router;
