import { ROUTES } from "@/constants/routes";

import type { V3ModuleMetadata } from "./module-types";

const allModes = [
  "restaurant",
  "retail",
  "raw-material",
  "custom-business",
] as const;

const nonRetailModes = ["restaurant", "raw-material", "custom-business"] as const;
const cashierShiftModes = ["restaurant", "retail"] as const;

export const businessModules: readonly V3ModuleMetadata[] = [
  {
    id: "employees",
    label: "Employees",
    description: "Planned shared employee management module.",
    layer: "business",
    status: "planned",
    supportedModes: nonRetailModes,
    routeBase: "/v3/business/employees",
    sidebarGroup: "Shared Business",
    sidebarVisible: false,
    sidebarEntries: [
      {
        moduleId: "employees",
        label: "Team Management",
        description: "Hardcoded employee directory, department, role, workload, and onboarding dashboard.",
        routePath: ROUTES.TEAM_MANAGEMENT,
        group: "Shared Business",
        supportedModes: nonRetailModes,
        requiredPermissions: ["employees.manage"],
        featureFlags: [],
        order: 80,
      },
      {
        moduleId: "employees",
        label: "Employee Performance",
        description: "Hardcoded performance scorecard and KPI planning dashboard.",
        routePath: ROUTES.EMPLOYEE_PERFORMANCE,
        group: "Shared Business",
        supportedModes: nonRetailModes,
        requiredPermissions: ["employees.manage"],
        featureFlags: [],
        order: 82,
      },
      {
        moduleId: "employees",
        label: "Employee Contracts",
        description: "Hardcoded contract register and renewal readiness dashboard.",
        routePath: ROUTES.EMPLOYEE_CONTRACTS,
        group: "Shared Business",
        supportedModes: nonRetailModes,
        requiredPermissions: ["employees.manage"],
        featureFlags: [],
        order: 84,
      },
      {
        moduleId: "employees",
        label: "Payroll",
        description: "Hardcoded payroll preview for salary, allowance, deduction, and approval readiness.",
        routePath: ROUTES.PAYROLL,
        group: "Shared Business",
        supportedModes: nonRetailModes,
        requiredPermissions: ["employees.manage"],
        featureFlags: [],
        order: 86,
      },
    ],
    requiredPermissions: ["employees.manage"],
    featureFlags: ["workforce-management"],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "attendance",
    label: "Attendance",
    description: "Planned attendance tracking module for workforce operations.",
    layer: "business",
    status: "planned",
    supportedModes: nonRetailModes,
    routeBase: "/v3/business/attendance",
    sidebarGroup: "Shared Business",
    sidebarVisible: false,
    sidebarEntries: [
      {
        moduleId: "attendance",
        label: "Employee Attendance",
        description: "Hardcoded check-in, check-out, missing attendance, and workforce visibility dashboard.",
        routePath: ROUTES.EMPLOYEE_ATTENDANCE,
        group: "Shared Business",
        supportedModes: nonRetailModes,
        requiredPermissions: ["attendance.manage"],
        featureFlags: [],
        order: 88,
      },
    ],
    requiredPermissions: ["attendance.manage"],
    featureFlags: ["workforce-management"],
    dependencies: ["auth", "permissions", "employees"],
  },
  {
    id: "shifts",
    label: "Cashier Shift Reports",
    description: "Shared shift reporting workspace for cashier performance and reconciliation.",
    layer: "business",
    status: "active",
    supportedModes: cashierShiftModes,
    routeBase: ROUTES.CASHIER_SHIFT_REPORTS,
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 70,
    workspaceOrder: 70,
    sidebarEntries: [
      {
        moduleId: "shifts",
        label: "Shift Reports",
        description: "Hardcoded shared closing summary for shift revenue, variance, and operations review.",
        routePath: ROUTES.OPERATION_REPORTS,
        group: "Shared Business",
        supportedModes: cashierShiftModes,
        requiredPermissions: ["shifts.manage"],
        featureFlags: [],
        order: 72,
      },
      {
        moduleId: "shifts",
        label: "Shift Overview",
        description: "Hardcoded roster coverage, open slot, and schedule risk dashboard.",
        routePath: ROUTES.ROSTER_OVERVIEW,
        group: "Shared Business",
        supportedModes: nonRetailModes,
        requiredPermissions: ["shifts.manage"],
        featureFlags: [],
        order: 74,
      },
    ],
    requiredPermissions: ["shifts.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "payments"],
  },
  {
    id: "reports",
    label: "Financial Reports",
    description: "Shared reporting workspace for financial summaries and profit analysis.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: ROUTES.FINANCIAL_REPORTS,
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 50,
    workspaceOrder: 50,
    sidebarEntries: [
      {
        moduleId: "reports",
        label: "HPP Calculator",
        description: "Hardcoded cost-of-goods calculator for unit cost, markup, and selling price planning.",
        routePath: ROUTES.HPP_CALCULATOR,
        group: "Shared Business",
        supportedModes: allModes,
        requiredPermissions: ["reports.view"],
        featureFlags: [],
        order: 52,
      },
    ],
    requiredPermissions: ["reports.view"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "analytics", "cashflow"],
  },
  {
    id: "customers",
    label: "Customers & Partners",
    description: "Shared customer and partner management workspace.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: ROUTES.CUSTOMERS,
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 20,
    workspaceOrder: 20,
    requiredPermissions: ["customers.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "cashflow",
    label: "Cashflow",
    description: "Shared cashflow workspace for income, expenses, and balances.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: ROUTES.CASHFLOW,
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 40,
    workspaceOrder: 40,
    requiredPermissions: ["cashflow.view"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "payments"],
  },
  {
    id: "invoice",
    label: "Invoice Generator",
    description: "Shared invoice generation workspace for previewing, saving, and downloading invoices.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: ROUTES.INVOICE_GENERATOR,
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 60,
    workspaceOrder: 60,
    requiredPermissions: ["invoice.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "customers", "payments"],
  },
] satisfies readonly V3ModuleMetadata[];
