import type { V3ModuleMetadata } from "./module-types";

const allModes = [
  "restaurant",
  "retail",
  "raw-material",
  "custom-business",
] as const;

export const businessModules: readonly V3ModuleMetadata[] = [
  {
    id: "employees",
    label: "Employees",
    description: "Planned shared employee management module.",
    layer: "business",
    status: "planned",
    supportedModes: allModes,
    routeBase: "/v3/business/employees",
    sidebarGroup: "Shared Business",
    sidebarVisible: false,
    requiredPermissions: ["employees.manage"],
    featureFlags: ["workforce-management"],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "attendance",
    label: "Attendance",
    description: "Planned attendance tracking module for workforce operations.",
    layer: "business",
    status: "planned",
    supportedModes: allModes,
    routeBase: "/v3/business/attendance",
    sidebarGroup: "Shared Business",
    sidebarVisible: false,
    requiredPermissions: ["attendance.manage"],
    featureFlags: ["workforce-management"],
    dependencies: ["auth", "permissions", "employees"],
  },
  {
    id: "shifts",
    label: "Cashier Shift Reports",
    description: "Shared shift reporting workspace for cashier performance and reconciliation.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: "/dashboard/cashier-shift-reports",
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    requiredPermissions: ["shifts.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "payments"],
  },
  {
    id: "reports",
    label: "Financial Reports",
    description: "Shared reporting workspace for financial summaries and profit analysis.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: "/dashboard/financial-reports",
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    requiredPermissions: ["reports.view"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "analytics", "cashflow"],
  },
  {
    id: "customers",
    label: "Customers & Partners",
    description: "Shared customer and partner management workspace.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: "/dashboard/customers",
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    requiredPermissions: ["customers.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "cashflow",
    label: "Cashflow",
    description: "Shared cashflow workspace for income, expenses, and balances.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: "/dashboard/cashflow",
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    requiredPermissions: ["cashflow.view"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "payments"],
  },
  {
    id: "invoice",
    label: "Invoice Generator",
    description: "Shared invoice generation workspace for previewing, saving, and downloading invoices.",
    layer: "business",
    status: "active",
    supportedModes: allModes,
    routeBase: "/dashboard/invoice-generator",
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    requiredPermissions: ["invoice.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "customers", "payments"],
  },
] satisfies readonly V3ModuleMetadata[];
