import { ROUTES } from "@/constants/routes";

import type { V3ModuleMetadata } from "./module-types";

const allModes = [
  "restaurant",
  "retail",
  "raw-material",
  "custom-business",
] as const;

export const coreModules: readonly V3ModuleMetadata[] = [
  {
    id: "auth",
    label: "Auth",
    description: "Authentication foundation for login, session, and account access.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["auth.access"],
    featureFlags: [],
    dependencies: [],
  },
  {
    id: "permissions",
    label: "Permissions",
    description: "Central permission metadata for role-based access decisions.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["permissions.manage"],
    featureFlags: [],
    dependencies: ["auth"],
  },
  {
    id: "settings",
    label: "Settings",
    description: "Shared business and application configuration foundation.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    sidebarEntries: [
      {
        moduleId: "settings",
        label: "Internal Monitor",
        description: "UI-only control room for route readiness, API contracts, schema decisions, and release gates.",
        routePath: ROUTES.INTERNAL_MONITORING,
        group: "Core Systems",
        supportedModes: allModes,
        requiredPermissions: ["platform-admin.internal-monitoring.read"],
        featureFlags: [],
        order: 8,
      },
      {
        moduleId: "settings",
        label: "Admin Role Console",
        description: "Mock-only console for internal role assignment, access review, and permission template planning.",
        routePath: ROUTES.ADMIN_ROLE_CONSOLE,
        group: "Core Systems",
        supportedModes: allModes,
        requiredPermissions: ["settings.manage"],
        featureFlags: [],
        order: 9,
      },
      {
        moduleId: "settings",
        label: "Billing Operations Console",
        description: "Mock-only console for subscription health, invoice queues, payment risk, and billing API planning.",
        routePath: ROUTES.BILLING_OPERATIONS_CONSOLE,
        group: "Core Systems",
        supportedModes: allModes,
        requiredPermissions: ["settings.manage"],
        featureFlags: [],
        order: 10,
      },
      {
        moduleId: "settings",
        label: "Support / Ops Console",
        description: "Mock-only console for tenant diagnostics, support queue, route access checks, and recovery planning.",
        routePath: ROUTES.OPERATOR_SUPPORT_CONSOLE,
        group: "Core Systems",
        supportedModes: allModes,
        requiredPermissions: ["settings.manage"],
        featureFlags: [],
        order: 11,
      },
      {
        moduleId: "settings",
        label: "Admin Action Audit",
        description: "Mock-only console for append-only admin action review and future evidence exports.",
        routePath: ROUTES.ADMIN_ACTION_AUDIT_CONSOLE,
        group: "Core Systems",
        supportedModes: allModes,
        requiredPermissions: ["settings.manage"],
        featureFlags: [],
        order: 12,
      },
      {
        moduleId: "settings",
        label: "Sensitive Action Approval",
        description: "Mock-only console for high-risk internal action requests, second approver checks, and rollback planning.",
        routePath: ROUTES.APPROVAL_CONTROL_CONSOLE,
        group: "Core Systems",
        supportedModes: allModes,
        requiredPermissions: ["settings.manage"],
        featureFlags: [],
        order: 13,
      },
    ],
    requiredPermissions: ["settings.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "inventory",
    label: "Inventory",
    description: "Reusable inventory engine and active inventory dashboard metadata.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: ROUTES.INVENTORY,
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 30,
    workspaceOrder: 30,
    requiredPermissions: ["inventory.view"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "payments",
    label: "Payments",
    description:
      "Reusable payment capability metadata. Restaurant V3 keeps payments under the Restaurant server workspace.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["payments.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "settings"],
  },
  {
    id: "analytics",
    label: "Sales Analytics",
    description: "Shared analytics dashboard metadata for sales, operational summaries, and role-scoped profit visibility.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: ROUTES.ANALYTICS,
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 10,
    workspaceOrder: 10,
    sidebarEntries: [
      {
        moduleId: "analytics",
        label: "Overview",
        description: "Hardcoded shared business dashboard for cross-mode KPI and module navigation demos.",
        routePath: ROUTES.BUSINESS_OVERVIEW,
        group: "Shared Business",
        supportedModes: allModes,
        requiredPermissions: ["analytics.operational-view"],
        featureFlags: [],
        order: 5,
      },
    ],
    requiredPermissions: ["analytics.operational-view"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "audit",
    label: "Audit",
    description: "Planned audit trail system for tracking important business events.",
    layer: "core",
    status: "planned",
    supportedModes: allModes,
    routeBase: "/v3/core/audit",
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    sidebarEntries: [
      {
        moduleId: "audit",
        label: "Audit Log",
        description: "Hardcoded audit event dashboard for important business actions and future append-only history.",
        routePath: ROUTES.AUDIT_LOG,
        group: "Shared Business",
        supportedModes: allModes,
        requiredPermissions: ["audit.view"],
        featureFlags: [],
        order: 90,
      },
      {
        moduleId: "audit",
        label: "Approval Center",
        description: "Hardcoded approval queue for purchase, payroll, contract, and operation exceptions.",
        routePath: ROUTES.APPROVALS,
        group: "Shared Business",
        supportedModes: allModes,
        requiredPermissions: ["audit.view"],
        featureFlags: [],
        order: 92,
      },
    ],
    requiredPermissions: ["audit.view"],
    featureFlags: ["audit-trail"],
    dependencies: ["auth", "permissions"],
  },
] as const;
