import type { V3ModuleMetadata } from "./module-types";

const allModes = [
  "restaurant",
  "retail",
  "raw-material",
  "custom-business",
] as const;

export const coreModules: readonly V3ModuleMetadata[] = [
  {
    id: "auth",
    label: "Auth",
    description: "Authentication foundation for login, session, and account access.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["auth.access"],
    featureFlags: [],
    dependencies: [],
  },
  {
    id: "permissions",
    label: "Permissions",
    description: "Central permission metadata for role-based access decisions.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["permissions.manage"],
    featureFlags: [],
    dependencies: ["auth"],
  },
  {
    id: "settings",
    label: "Settings",
    description: "Shared business and application configuration foundation.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["settings.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "inventory",
    label: "Inventory",
    description: "Reusable inventory engine and active inventory dashboard metadata.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: "/dashboard/inventory",
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 30,
    workspaceOrder: 30,
    requiredPermissions: ["inventory.view"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "payments",
    label: "Payments",
    description:
      "Reusable payment capability metadata. Restaurant V3 does not expose a main payments nav item yet; the legacy F&B payment route remains a manual fallback.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: null,
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["payments.manage"],
    featureFlags: [],
    dependencies: ["auth", "permissions", "settings"],
  },
  {
    id: "analytics",
    label: "Sales Analytics",
    description: "Shared analytics dashboard metadata for sales, operational summaries, and role-scoped profit visibility.",
    layer: "core",
    status: "active",
    supportedModes: allModes,
    routeBase: "/dashboard/analytics",
    sidebarGroup: "Shared Business",
    sidebarVisible: true,
    sidebarOrder: 10,
    workspaceOrder: 10,
    requiredPermissions: ["analytics.operational-view"],
    featureFlags: [],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "audit",
    label: "Audit",
    description: "Planned audit trail system for tracking important business events.",
    layer: "core",
    status: "planned",
    supportedModes: allModes,
    routeBase: "/v3/core/audit",
    sidebarGroup: "Core Systems",
    sidebarVisible: false,
    requiredPermissions: ["audit.view"],
    featureFlags: ["audit-trail"],
    dependencies: ["auth", "permissions"],
  },
] satisfies readonly V3ModuleMetadata[];
