import type { V3ModuleMetadata } from "./module-types";

const rawMaterialMode = ["raw-material"] as const;

export const rawMaterialModules: readonly V3ModuleMetadata[] = [
  {
    id: "intake",
    label: "Supplier Intake",
    description: "Raw-material intake preview for receiving supplier goods.",
    layer: "raw-material",
    status: "active",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/intake",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    sidebarOrder: 10,
    workspaceOrder: 10,
    requiredPermissions: ["raw-material.intake.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "suppliers"],
  },
  {
    id: "weighing",
    label: "Weighing",
    description: "Raw-material weighing preview for gross, tare, and net weight tracking.",
    layer: "raw-material",
    status: "active",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/weighing",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    sidebarOrder: 20,
    workspaceOrder: 20,
    requiredPermissions: ["raw-material.weighing.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "batches"],
  },
  {
    id: "batches",
    label: "Batches",
    description: "Raw-material batch and lot inventory preview.",
    layer: "raw-material",
    status: "active",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/batches",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    sidebarOrder: 30,
    workspaceOrder: 30,
    requiredPermissions: ["raw-material.batches.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "suppliers"],
  },
  {
    id: "storage",
    label: "Storage",
    description: "Raw-material storage and cold-storage preview for stock control.",
    layer: "raw-material",
    status: "active",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/storage",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    sidebarOrder: 40,
    workspaceOrder: 40,
    requiredPermissions: ["raw-material.storage.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "batches"],
  },
  {
    id: "processing",
    label: "Processing",
    description: "Raw-material processing preview for transformation and yield tracking.",
    layer: "raw-material",
    status: "active",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/processing",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    sidebarOrder: 50,
    workspaceOrder: 50,
    requiredPermissions: ["raw-material.processing.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "batches", "storage"],
  },
  {
    id: "kandang",
    label: "Kandang",
    description: "Livestock and pen management preview.",
    layer: "raw-material",
    status: "active",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/kandang",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    sidebarOrder: 60,
    workspaceOrder: 60,
    requiredPermissions: ["raw-material.kandang.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "suppliers"],
  },
  {
    id: "suppliers",
    label: "Suppliers",
    description: "Raw-material supplier preview for intake source management.",
    layer: "raw-material",
    status: "active",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/suppliers",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    sidebarOrder: 70,
    workspaceOrder: 70,
    requiredPermissions: ["raw-material.suppliers.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["auth", "permissions"],
  },
] satisfies readonly V3ModuleMetadata[];
