import type { V3ModuleMetadata } from "./module-types";

const rawMaterialMode = ["raw-material"] as const;

export const rawMaterialModules: readonly V3ModuleMetadata[] = [
  {
    id: "intake",
    label: "Supplier Intake",
    description: "Planned raw-material intake workspace for receiving supplier goods.",
    layer: "raw-material",
    status: "planned",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/intake",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    requiredPermissions: ["raw-material.intake.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "suppliers"],
  },
  {
    id: "weighing",
    label: "Weighing",
    description: "Planned weighing workspace for gross, tare, and net weight tracking.",
    layer: "raw-material",
    status: "planned",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/weighing",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    requiredPermissions: ["raw-material.weighing.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "batches"],
  },
  {
    id: "batches",
    label: "Batches",
    description: "Planned batch and lot inventory workspace.",
    layer: "raw-material",
    status: "planned",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/batches",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    requiredPermissions: ["raw-material.batches.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "suppliers"],
  },
  {
    id: "storage",
    label: "Storage",
    description: "Planned storage and cold-storage workspace for raw material stock.",
    layer: "raw-material",
    status: "planned",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/storage",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    requiredPermissions: ["raw-material.storage.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "batches"],
  },
  {
    id: "processing",
    label: "Processing",
    description: "Planned transformation workflow for raw material processing and yield tracking.",
    layer: "raw-material",
    status: "planned",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/processing",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    requiredPermissions: ["raw-material.processing.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "batches", "storage"],
  },
  {
    id: "kandang",
    label: "Kandang",
    description: "Planned livestock and pen management workspace.",
    layer: "raw-material",
    status: "planned",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/kandang",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    requiredPermissions: ["raw-material.kandang.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["inventory", "suppliers"],
  },
  {
    id: "suppliers",
    label: "Suppliers",
    description: "Planned raw-material supplier workspace for intake source management.",
    layer: "raw-material",
    status: "planned",
    supportedModes: rawMaterialMode,
    routeBase: "/v3/raw-material/suppliers",
    sidebarGroup: "Raw Material Operations",
    sidebarVisible: true,
    requiredPermissions: ["raw-material.suppliers.manage"],
    featureFlags: ["raw-material-mode"],
    dependencies: ["auth", "permissions"],
  },
] satisfies readonly V3ModuleMetadata[];
