import type { V3ModuleMetadata } from "./module-types";

const restaurantMode = ["restaurant"] as const;

export const restaurantModules: readonly V3ModuleMetadata[] = [
  {
    id: "pos",
    label: "POS Workspace",
    description: "Restaurant cashier workspace for cart, order entry, payment handoff, and receipt flow.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: "/dashboard/fnb/server/checkout",
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    requiredPermissions: ["restaurant.pos.access"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["payments", "inventory", "customers", "tables", "menu", "orders"],
  },
  {
    id: "kitchen",
    label: "Kitchen",
    description: "Restaurant kitchen display workspace for preparing active orders.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: "/dashboard/fnb/kitchen",
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    requiredPermissions: ["restaurant.kitchen.access"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["orders", "menu"],
  },
  {
    id: "serving",
    label: "Serving",
    description: "Restaurant serving queue workspace for ready orders and table delivery.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: "/dashboard/fnb/server/serving",
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    requiredPermissions: ["restaurant.serving.access"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["orders", "tables"],
  },
  {
    id: "tables",
    label: "Tables",
    description: "Restaurant table management workspace for dining room operations.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: "/dashboard/fnb/server/tables",
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    requiredPermissions: ["restaurant.tables.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "menu",
    label: "Menu",
    description: "Restaurant menu management workspace for sellable food and beverage items.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: "/dashboard/fnb/menu",
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    requiredPermissions: ["restaurant.menu.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["inventory"],
  },
  {
    id: "recipes",
    label: "Recipes",
    description: "Restaurant recipe workspace for ingredient usage and menu inventory deduction.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: "/dashboard/fnb/menu/recipes",
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    requiredPermissions: ["restaurant.recipes.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["inventory", "menu"],
  },
  {
    id: "orders",
    label: "Orders",
    description: "Restaurant order management workspace for active and completed orders.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: "/dashboard/fnb/server/orders",
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    requiredPermissions: ["restaurant.orders.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["payments", "inventory", "customers", "tables", "menu"],
  },
] satisfies readonly V3ModuleMetadata[];
