import type { V3ModuleMetadata } from "./module-types";
import { ROUTES } from "../../constants/routes";

const restaurantMode = ["restaurant"] as const;

// V3 workspaces are now the main Restaurant navigation targets.
// Legacy /dashboard/fnb routes remain registered in App.tsx as manual fallback URLs.

export const restaurantModules: readonly V3ModuleMetadata[] = [
  {
    id: "pos",
    label: "POS Workspace",
    description: "Restaurant cashier workspace for cart, order entry, payment handoff, and receipt flow.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: ROUTES.WORKSPACE_RESTAURANT_POS,
    workspaceRoute: ROUTES.WORKSPACE_RESTAURANT_POS,
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    sidebarLabel: "Cashier",
    sidebarOrder: 110,
    workspaceOrder: 110,
    requiredPermissions: ["restaurant.pos.access"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["payments", "inventory", "customers", "tables", "menu", "orders"],
  },
  {
    id: "kitchen",
    label: "Kitchen",
    description: "Restaurant kitchen display workspace for preparing active orders.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: ROUTES.WORKSPACE_RESTAURANT_KITCHEN,
    workspaceRoute: ROUTES.WORKSPACE_RESTAURANT_KITCHEN,
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    sidebarLabel: "Kitchen (KDS)",
    sidebarOrder: 180,
    workspaceOrder: 180,
    requiredPermissions: ["restaurant.kitchen.access"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["orders", "menu"],
  },
  {
    id: "serving",
    label: "Serving",
    description: "Restaurant serving queue workspace for ready orders and table delivery.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: ROUTES.WORKSPACE_RESTAURANT_SERVING,
    workspaceRoute: ROUTES.WORKSPACE_RESTAURANT_SERVING,
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    sidebarOrder: 130,
    workspaceOrder: 130,
    requiredPermissions: ["restaurant.serving.access"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["orders", "tables"],
  },
  {
    id: "tables",
    label: "Tables",
    description: "Restaurant table management workspace for dining room operations.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: ROUTES.WORKSPACE_RESTAURANT_TABLES,
    workspaceRoute: ROUTES.WORKSPACE_RESTAURANT_TABLES,
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    sidebarOrder: 140,
    workspaceOrder: 140,
    requiredPermissions: ["restaurant.tables.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["auth", "permissions"],
  },
  {
    id: "menu",
    label: "Menu",
    description: "Restaurant menu management workspace for sellable food and beverage items.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: ROUTES.WORKSPACE_RESTAURANT_MENU,
    workspaceRoute: ROUTES.WORKSPACE_RESTAURANT_MENU,
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    sidebarOrder: 160,
    workspaceOrder: 160,
    requiredPermissions: ["restaurant.menu.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["inventory"],
  },
  {
    id: "recipes",
    label: "Recipes",
    description: "Restaurant recipe workspace for ingredient usage and menu inventory deduction.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: ROUTES.WORKSPACE_RESTAURANT_RECIPES,
    workspaceRoute: ROUTES.WORKSPACE_RESTAURANT_RECIPES,
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    sidebarOrder: 170,
    workspaceOrder: 170,
    requiredPermissions: ["restaurant.recipes.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["inventory", "menu"],
  },
  {
    id: "orders",
    label: "Orders",
    description: "Restaurant order management workspace for active and completed orders.",
    layer: "restaurant",
    status: "active",
    supportedModes: restaurantMode,
    routeBase: ROUTES.WORKSPACE_RESTAURANT_ORDERS,
    workspaceRoute: ROUTES.WORKSPACE_RESTAURANT_ORDERS,
    sidebarGroup: "Restaurant Operations",
    sidebarVisible: true,
    sidebarOrder: 120,
    workspaceOrder: 120,
    requiredPermissions: ["restaurant.orders.manage"],
    featureFlags: ["restaurant-mode"],
    dependencies: ["payments", "inventory", "customers", "tables", "menu"],
  },
] satisfies readonly V3ModuleMetadata[];
