import type { V3ModuleMetadata } from "./module-types";

const retailMode = ["retail"] as const;

export const retailModules: readonly V3ModuleMetadata[] = [
  {
    id: "cashier",
    label: "Cashier",
    description: "Planned retail cashier workspace for barcode-first fast checkout.",
    layer: "retail",
    status: "planned",
    supportedModes: retailMode,
    routeBase: "/v3/retail/cashier",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    requiredPermissions: ["retail.cashier.access"],
    featureFlags: ["retail-mode"],
    dependencies: ["payments", "inventory", "customers", "catalog", "barcode"],
  },
  {
    id: "catalog",
    label: "Product Catalog",
    description: "Planned retail product catalog workspace for SKU and variant management.",
    layer: "retail",
    status: "planned",
    supportedModes: retailMode,
    routeBase: "/v3/retail/catalog",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    requiredPermissions: ["retail.catalog.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory"],
  },
  {
    id: "barcode",
    label: "Barcode / SKU",
    description: "Planned barcode and SKU workflow metadata for retail item lookup.",
    layer: "retail",
    status: "planned",
    supportedModes: retailMode,
    routeBase: "/v3/retail/barcode",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    requiredPermissions: ["retail.barcode.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["catalog", "inventory"],
  },
  {
    id: "receiving",
    label: "Receiving",
    description: "Planned retail receiving workspace for supplier stock intake.",
    layer: "retail",
    status: "planned",
    supportedModes: retailMode,
    routeBase: "/v3/retail/receiving",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    requiredPermissions: ["retail.receiving.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "catalog"],
  },
  {
    id: "stock-opname",
    label: "Stock Opname",
    description: "Planned retail stock count and adjustment workspace.",
    layer: "retail",
    status: "planned",
    supportedModes: retailMode,
    routeBase: "/v3/retail/stock-opname",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    requiredPermissions: ["retail.stock-opname.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "catalog"],
  },
  {
    id: "shelf-management",
    label: "Shelf Management",
    description: "Planned retail shelf, rack, and bin location workspace.",
    layer: "retail",
    status: "planned",
    supportedModes: retailMode,
    routeBase: "/v3/retail/shelf-management",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    requiredPermissions: ["retail.shelf-management.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "catalog"],
  },
  {
    id: "promotions",
    label: "Promotions",
    description: "Planned retail promotion and discount rule workspace.",
    layer: "retail",
    status: "planned",
    supportedModes: retailMode,
    routeBase: "/v3/retail/promotions",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    requiredPermissions: ["retail.promotions.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["catalog", "payments"],
  },
] satisfies readonly V3ModuleMetadata[];
