import type { V3ModuleMetadata } from "./module-types";

const retailMode = ["retail"] as const;

export const retailModules: readonly V3ModuleMetadata[] = [
  {
    id: "cashier",
    label: "Retail Cashier",
    description: "Barcode-first retail cashier. Fetches live products from the Prisma API and persists checkouts with stock deduction and cashflow entry.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/cashier",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    sidebarOrder: 10,
    requiredPermissions: ["retail.cashier.access"],
    featureFlags: ["retail-mode"],
    dependencies: ["payments", "inventory", "customers", "catalog", "barcode"],
  },
  {
    id: "catalog",
    label: "Product Catalog",
    description: "Retail product catalog. Fetches live SKU, barcode, stock, and shelf data from the Prisma API with stock-status filtering.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/catalog",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    sidebarOrder: 20,
    requiredPermissions: ["retail.catalog.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory"],
  },
  {
    id: "barcode",
    label: "Barcode / SKU",
    description: "Barcode and SKU lookup workspace. Interactive barcode scan simulation backed by the retail product catalog.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/barcode",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    sidebarOrder: 30,
    requiredPermissions: ["retail.barcode.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["catalog", "inventory"],
  },
  {
    id: "receiving",
    label: "Receiving",
    description: "Supplier stock intake workspace. Fetches the receiving queue from the Prisma API and enforces guarded status transitions (draft → ordered → partial → received).",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/receiving",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    sidebarOrder: 40,
    requiredPermissions: ["retail.receiving.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "catalog"],
  },
  {
    id: "stock-opname",
    label: "Stock Opname",
    description: "Retail stock count and adjustment workspace. Interactive mock — no dedicated stock-count API endpoints exist yet.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/stock-opname",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    sidebarOrder: 50,
    requiredPermissions: ["retail.stock-opname.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "catalog"],
  },
  {
    id: "shelf-management",
    label: "Shelf Management",
    description: "Retail shelf, rack, and bin location workspace. Interactive mock — no dedicated shelf-management API endpoints exist yet.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/shelf-management",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    sidebarOrder: 60,
    requiredPermissions: ["retail.shelf-management.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "catalog"],
  },
  {
    id: "promotions",
    label: "Promotions",
    description: "Retail promotion and discount rule workspace. Interactive mock — no dedicated promotions API endpoints exist yet.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/promotions",
    sidebarGroup: "Retail Operations",
    sidebarVisible: true,
    sidebarOrder: 70,
    requiredPermissions: ["retail.promotions.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["catalog", "payments"],
  },
  {
    id: "customers-loyalty",
    label: "Customers & Loyalty",
    description: "Customer CRM, member points, repeat rate, and loyalty liability dashboard. Retail Growth layer — demo data only.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/customers-loyalty",
    sidebarGroup: "Retail Growth",
    sidebarVisible: true,
    sidebarOrder: 80,
    requiredPermissions: ["retail.customers.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["cashier", "customers", "promotions"],
  },
  {
    id: "returns-exchanges",
    label: "Returns & Exchanges",
    description: "Return desk wired to the Prisma API. Previews restockability and manager review requirements, then persists the return with stock reversal and cashflow entry.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/returns-exchanges",
    sidebarGroup: "Retail Growth",
    sidebarVisible: true,
    sidebarOrder: 90,
    requiredPermissions: ["retail.returns.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["cashier", "inventory", "approvals"],
  },
  {
    id: "staff-shifts",
    label: "Retail Staff & Shifts",
    description: "Retail staff shifts, register variance, handover, and staff performance dashboard. Retail Growth layer — demo data only.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/staff-shifts",
    sidebarGroup: "Retail Growth",
    sidebarVisible: true,
    sidebarOrder: 100,
    requiredPermissions: ["retail.staff.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["cashier", "employees", "shifts"],
  },
  {
    id: "forecasting",
    label: "Forecasting",
    description: "Retail demand planning, reorder, dead stock, fast mover, and purchase budget dashboard. Retail Growth layer — demo data only.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/forecasting",
    sidebarGroup: "Retail Growth",
    sidebarVisible: true,
    sidebarOrder: 110,
    requiredPermissions: ["retail.forecasting.view"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "receiving", "analytics"],
  },
  {
    id: "multi-location",
    label: "Multi-location",
    description: "Branch dashboard for outlet comparison, transfer needs, and branch stock health. Retail Enterprise layer — demo data only.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/multi-location",
    sidebarGroup: "Retail Enterprise",
    sidebarVisible: true,
    sidebarOrder: 120,
    requiredPermissions: ["retail.locations.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["inventory", "analytics", "transfers"],
  },
  {
    id: "omnichannel",
    label: "Omnichannel Orders",
    description: "Online channel, marketplace, pickup, and stock reservation dashboard. Retail Enterprise layer — demo data only.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/omnichannel",
    sidebarGroup: "Retail Enterprise",
    sidebarVisible: true,
    sidebarOrder: 130,
    requiredPermissions: ["retail.omnichannel.manage"],
    featureFlags: ["retail-mode"],
    dependencies: ["orders", "inventory", "customers"],
  },
  {
    id: "audit-controls",
    label: "Audit Controls",
    description: "Review dashboard for voids, refunds, price overrides, stock variance, and approvals. Retail Enterprise layer — demo data only.",
    layer: "retail",
    status: "active",
    supportedModes: retailMode,
    routeBase: "/v3/retail/audit-controls",
    sidebarGroup: "Retail Enterprise",
    sidebarVisible: true,
    sidebarOrder: 140,
    requiredPermissions: ["retail.audit.view"],
    featureFlags: ["retail-mode"],
    dependencies: ["approvals", "audit-log", "inventory"],
  },
] satisfies readonly V3ModuleMetadata[];
