import type { RawMaterialApiContract } from "./raw-material.types";

export const rawMaterialApiContracts: readonly RawMaterialApiContract[] = [
  {
    id: "rm-api-summary",
    moduleId: "intake",
    operationId: "rawMaterialGetSummary",
    method: "GET",
    path: "/raw-material/summary",
    purpose: "Read backend-backed raw material dashboard summary for shared workspace metrics.",
    requestShape: "Headers: X-Business-Mode=raw-material; Cookie session",
    responseShape: "{ success, data: RawMaterialSummaryResponse }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-suppliers-list",
    moduleId: "suppliers",
    operationId: "rawMaterialListSuppliers",
    method: "GET",
    path: "/raw-material/suppliers",
    purpose: "List supplier identities, source category, lead time, and reliability score for supplier filters and intake context.",
    requestShape: "Query: includeInactive?, search?",
    responseShape: "{ success, data: RawMaterialSupplierDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-storage-list",
    moduleId: "storage",
    operationId: "rawMaterialListStorageLocations",
    method: "GET",
    path: "/raw-material/storage-locations",
    purpose: "List raw material storage capacity, usage, and type metadata for storage cards and transfer preview selectors.",
    requestShape: "Query: includeInactive?, search?",
    responseShape: "{ success, data: RawMaterialStorageLocationDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-intake-list",
    moduleId: "intake",
    operationId: "rawMaterialListIntakes",
    method: "GET",
    path: "/raw-material/intakes",
    purpose: "List supplier intake rows with supplier, quantity, quality, and target storage metadata.",
    requestShape: "Query: status?, supplierId?, targetStorageLocationId?, search?",
    responseShape: "{ success, data: RawMaterialIntakeDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-weighing-list",
    moduleId: "weighing",
    operationId: "rawMaterialListWeighings",
    method: "GET",
    path: "/raw-material/weighings",
    purpose: "List weighing records for gross, tare, net, station, operator, and intake linkage read surfaces.",
    requestShape: "Query: intakeId?, stationName?, operatorName?, search?",
    responseShape: "{ success, data: RawMaterialWeighingDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-batches-list",
    moduleId: "batches",
    operationId: "rawMaterialListBatches",
    method: "GET",
    path: "/raw-material/batches",
    purpose: "List lot-controlled raw-material batches for traceability, expiry monitoring, and preview selector hydration.",
    requestShape: "Query: intakeId?, storageLocationId?, qualityStatus?, isActive?, search?",
    responseShape: "{ success, data: RawMaterialBatchDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-processing-list",
    moduleId: "processing",
    operationId: "rawMaterialListProcessingRuns",
    method: "GET",
    path: "/raw-material/processing-runs",
    purpose: "List raw-to-output transformation runs for processing snapshots and status-read surfaces.",
    requestShape: "Query: inputBatchId?, status?, search?",
    responseShape: "{ success, data: RawMaterialProcessingRunDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-kandang-list",
    moduleId: "kandang",
    operationId: "rawMaterialListPens",
    method: "GET",
    path: "/raw-material/pens",
    purpose: "List pen capacity, flock, occupancy, feed batch, and health status for livestock support mode.",
    requestShape: "Query: healthStatus?, feedBatchId?, isActive?, search?",
    responseShape: "{ success, data: RawMaterialKandangPenDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-stock-movement-list",
    moduleId: "storage",
    operationId: "rawMaterialListStockMovements",
    method: "GET",
    path: "/raw-material/stock-movements",
    purpose: "List stock movement ledger rows for transfer, adjustment, receiving, and processing-consumption read surfaces.",
    requestShape: "Query: batchId?, type?, reason?, source?, sourceId?, storageLocationId?, search?",
    responseShape: "{ success, data: RawMaterialStockMovementDto[] }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-intake-preview",
    moduleId: "intake",
    operationId: "rawMaterialPreviewIntake",
    method: "POST",
    path: "/raw-material/previews/intake",
    purpose: "Preview intake quantity, supplier, target storage capacity, and acceptance estimates before local draft/write UX continues.",
    requestShape: "Body: materialName, supplierId, targetStorageLocationId, receivedQuantity, acceptedQuantity?, rejectedQuantity?, unit?",
    responseShape: "{ success, data: RawMaterialPreviewResult<IntakeEstimates> }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-batch-preview",
    moduleId: "batches",
    operationId: "rawMaterialPreviewBatch",
    method: "POST",
    path: "/raw-material/previews/batch",
    purpose: "Preview batch creation against intake accepted quantity, lot-code conflict, storage validity, and batch quality state.",
    requestShape: "Body: lotCode?, intakeId, storageLocationId, quantity, remainingQuantity?, qualityStatus?",
    responseShape: "{ success, data: RawMaterialPreviewResult<BatchEstimates> }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-processing-preview",
    moduleId: "processing",
    operationId: "rawMaterialPreviewProcessingRun",
    method: "POST",
    path: "/raw-material/previews/processing-run",
    purpose: "Preview processing input, output, byproduct, waste, yield, batch remaining quantity, and storage impact before write UX is enabled.",
    requestShape: "Body: inputBatchId, outputName?, inputQuantity, outputQuantity?, byproductQuantity?, wasteQuantity?, expectedYieldPercent?, status?",
    responseShape: "{ success, data: RawMaterialPreviewResult<ProcessingEstimates> }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-intake-create",
    moduleId: "intake",
    operationId: "rawMaterialCreateIntake",
    method: "POST",
    path: "/raw-material/intakes",
    purpose: "Create an intake record with received, accepted, rejected quantity, supplier, and storage target. Backend exists; frontend write UX remains disabled until preview/write delegates exist.",
    requestShape: "Body: referenceNumber, supplierId, materialName, unit, receivedQuantity, acceptedQuantity, rejectedQuantity, qualityStatus, targetStorageLocationId, receivedAt?",
    responseShape: "{ success, data: RawMaterialIntakeDto }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-weighing-create",
    moduleId: "weighing",
    operationId: "rawMaterialCreateWeighing",
    method: "POST",
    path: "/raw-material/weighings",
    purpose: "Record gross, tare, net, station, operator, and intake linkage. Backend exists; frontend write UX remains disabled until preview/write delegates exist.",
    requestShape: "Body: referenceNumber, intakeId, stationName, grossKg, tareKg, operatorName, measuredAt?",
    responseShape: "{ success, data: RawMaterialWeighingDto }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-storage-transfer",
    moduleId: "storage",
    operationId: "rawMaterialTransferStock",
    method: "POST",
    path: "/raw-material/stock-movements/transfer",
    purpose: "Transfer raw material batch stock between storage locations through guarded stock movement ledger. Backend exists; frontend write UX remains disabled until preview/write delegates exist.",
    requestShape: "Body: batchId, sourceStorageLocationId, targetStorageLocationId, quantity, note?",
    responseShape: "{ success, data: { outMovement, inMovement, batch } }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-processing-run",
    moduleId: "processing",
    operationId: "rawMaterialCreateProcessingRun",
    method: "POST",
    path: "/raw-material/processing-runs",
    purpose: "Create a raw-to-output transformation run with input batch, output, byproduct, waste, and status guards. Backend exists; frontend write UX remains disabled until preview/write delegates exist.",
    requestShape: "Body: runNumber, inputBatchId, outputName, inputQuantity, outputQuantity, byproductQuantity?, wasteQuantity?, status?, startedAt?",
    responseShape: "{ success, data: RawMaterialProcessingRunDto }",
    persistence: "backend-backed",
  },
];
