import type { RawMaterialApiContract } from "./raw-material.types";

export const rawMaterialApiContracts: readonly RawMaterialApiContract[] = [
  {
    id: "rm-api-summary",
    moduleId: "intake",
    method: "GET",
    path: "/raw-material/summary",
    purpose: "Read backend-backed raw material dashboard summary for shared workspace metrics.",
    requestShape: "Headers: X-Business-Mode=raw-material; Cookie session",
    responseShape: "{ success, data: RawMaterialSummaryResponse }",
    persistence: "backend-backed-with-mock-fallback",
  },
  {
    id: "rm-api-intake-list",
    moduleId: "intake",
    method: "GET",
    path: "/raw-material/intakes",
    purpose: "List supplier intake rows with supplier, quantity, quality, and target storage metadata.",
    requestShape: "Query: status?, supplierId?, targetStorageLocationId?, search?",
    responseShape: "{ success, data: RawMaterialIntakeDto[] }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-intake-create",
    moduleId: "intake",
    method: "POST",
    path: "/raw-material/intakes",
    purpose: "Create an intake record with received, accepted, rejected quantity, supplier, and storage target.",
    requestShape: "Body: referenceNumber, supplierId, materialName, unit, receivedQuantity, acceptedQuantity, rejectedQuantity, qualityStatus, targetStorageLocationId, receivedAt?",
    responseShape: "{ success, data: RawMaterialIntakeDto }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-weighing-create",
    moduleId: "weighing",
    method: "POST",
    path: "/raw-material/weighings",
    purpose: "Record gross, tare, net, station, operator, and intake linkage.",
    requestShape: "Body: referenceNumber, intakeId, stationName, grossKg, tareKg, operatorName, measuredAt?",
    responseShape: "{ success, data: RawMaterialWeighingDto }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-batches-list",
    moduleId: "batches",
    method: "GET",
    path: "/raw-material/batches",
    purpose: "List lot-controlled raw-material batches for traceability and expiry monitoring.",
    requestShape: "Query: intakeId?, storageLocationId?, qualityStatus?, isActive?, search?",
    responseShape: "{ success, data: RawMaterialBatchDto[] }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-storage-transfer",
    moduleId: "storage",
    method: "POST",
    path: "/raw-material/stock-movements/transfer",
    purpose: "Transfer raw material batch stock between storage locations through guarded stock movement ledger.",
    requestShape: "Body: batchId, sourceStorageLocationId, targetStorageLocationId, quantity, note?",
    responseShape: "{ success, data: { outMovement, inMovement, batch } }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-processing-run",
    moduleId: "processing",
    method: "POST",
    path: "/raw-material/processing-runs",
    purpose: "Create a raw-to-output transformation run with input batch, output, byproduct, waste, and status guards.",
    requestShape: "Body: runNumber, inputBatchId, outputName, inputQuantity, outputQuantity, byproductQuantity?, wasteQuantity?, status?, startedAt?",
    responseShape: "{ success, data: RawMaterialProcessingRunDto }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-kandang-list",
    moduleId: "kandang",
    method: "GET",
    path: "/raw-material/pens",
    purpose: "List pen capacity, flock, occupancy, feed batch, and health status for livestock support mode.",
    requestShape: "Query: healthStatus?, feedBatchId?, isActive?, search?",
    responseShape: "{ success, data: RawMaterialKandangPenDto[] }",
    persistence: "backend-backed",
  },
  {
    id: "rm-api-suppliers-list",
    moduleId: "suppliers",
    method: "GET",
    path: "/raw-material/suppliers",
    purpose: "List supplier identities, source category, lead time, and reliability score.",
    requestShape: "Query: includeInactive?, search?",
    responseShape: "{ success, data: RawMaterialSupplierDto[] }",
    persistence: "backend-backed",
  },
];
