import type { RawMaterialApiContract } from "./raw-material.types";

export const rawMaterialApiContracts: readonly RawMaterialApiContract[] = [
  {
    id: "rm-api-intake-list",
    moduleId: "intake",
    method: "GET",
    path: "/api/v3/raw-material/intakes",
    purpose: "List supplier intake rows with supplier, quantity, quality, and target storage metadata.",
    requestShape: "Query: tenantId, dateFrom, dateTo, supplierId?, qualityStatus?",
    responseShape: "{ success, data: RawMaterialIntake[], meta: { total, mock: true } }",
    persistence: "mock-only",
  },
  {
    id: "rm-api-intake-create",
    moduleId: "intake",
    method: "POST",
    path: "/api/v3/raw-material/intakes",
    purpose: "Create a future intake draft without immediately mutating stock.",
    requestShape: "Body: supplierId, materialName, receivedQuantity, unit, targetStorageId, receivedAt",
    responseShape: "{ success, data: RawMaterialIntake, auditPreviewId }",
    persistence: "future-db",
  },
  {
    id: "rm-api-weighing-create",
    moduleId: "weighing",
    method: "POST",
    path: "/api/v3/raw-material/weighings",
    purpose: "Record gross, tare, net, station, operator, and intake linkage.",
    requestShape: "Body: intakeId, stationName, grossKg, tareKg, operatorId",
    responseShape: "{ success, data: RawMaterialWeighing, netKg }",
    persistence: "future-db",
  },
  {
    id: "rm-api-batches-list",
    moduleId: "batches",
    method: "GET",
    path: "/api/v3/raw-material/batches",
    purpose: "List lot-controlled raw-material batches for traceability and expiry monitoring.",
    requestShape: "Query: tenantId, materialName?, storageId?, qualityStatus?",
    responseShape: "{ success, data: RawMaterialBatch[], meta: { total, mock: true } }",
    persistence: "mock-only",
  },
  {
    id: "rm-api-storage-transfer",
    moduleId: "storage",
    method: "PATCH",
    path: "/api/v3/raw-material/storage/transfers/:id",
    purpose: "Future transfer approval between storage locations without changing the current schema yet.",
    requestShape: "Body: sourceStorageId, targetStorageId, batchId, quantityKg, reason",
    responseShape: "{ success, data: StorageTransferPreview, stockMovementPreview }",
    persistence: "future-db",
  },
  {
    id: "rm-api-processing-run",
    moduleId: "processing",
    method: "POST",
    path: "/api/v3/raw-material/processing-runs",
    purpose: "Create a raw-to-output transformation run with input batch, yield, and byproduct preview.",
    requestShape: "Body: inputBatchId, inputKg, outputName, plannedOutputKg, operatorId",
    responseShape: "{ success, data: RawMaterialProcessingRun, yieldPreview }",
    persistence: "future-db",
  },
  {
    id: "rm-api-kandang-list",
    moduleId: "kandang",
    method: "GET",
    path: "/api/v3/raw-material/kandang/pens",
    purpose: "List pen capacity, flock, occupancy, feed batch, and health status for livestock support mode.",
    requestShape: "Query: tenantId, healthStatus?, feedBatchId?",
    responseShape: "{ success, data: RawMaterialKandangPen[], meta: { total, mock: true } }",
    persistence: "mock-only",
  },
  {
    id: "rm-api-suppliers-list",
    moduleId: "suppliers",
    method: "GET",
    path: "/api/v3/raw-material/suppliers",
    purpose: "List supplier identities, source category, lead time, and reliability score.",
    requestShape: "Query: tenantId, category?, search?",
    responseShape: "{ success, data: RawMaterialSupplier[], meta: { total, mock: true } }",
    persistence: "mock-only",
  },
];
