import {
  permissionState,
  type PermissionActionId,
  type PermissionState,
  type SystemRole,
} from "./role-permission-library";

export type BusinessRoleSector =
  | "restaurant"
  | "retail"
  | "raw-material"
  | "custom-business";

export type JobRoleProfile = {
  id: string;
  sector: BusinessRoleSector;
  department: string;
  title: string;
  aliases: string[];
  baseRole: SystemRole;
  seniority: "owner" | "manager" | "supervisor" | "operator" | "staff" | "viewer";
  description: string;
  responsibilities: string[];
  recommendedPermissions: PermissionState;
};

type PermissionSeed = Record<string, PermissionActionId[]>;

function p(seed: PermissionSeed) {
  return permissionState(seed);
}

const managerOps = p({
  "business-overview": ["view", "export"],
  pos: ["view", "create", "update", "approve"],
  orders: ["view", "create", "update", "approve"],
  inventory: ["view", "create", "update", "approve"],
  production: ["view", "create", "update", "approve"],
  supplier: ["view", "create", "update", "approve"],
  cashflow: ["view"],
  reports: ["view", "export"],
  customers: ["view", "create", "update"],
  team: ["view", "update"],
  settings: ["view"],
});

const financeOps = p({
  "business-overview": ["view", "export"],
  orders: ["view"],
  inventory: ["view"],
  supplier: ["view"],
  cashflow: ["view", "create", "update", "delete", "export", "approve"],
  reports: ["view", "export", "approve"],
  customers: ["view"],
  team: ["view"],
  settings: ["view"],
});

const frontDeskOps = p({
  pos: ["view", "create", "update"],
  orders: ["view", "create", "update"],
  customers: ["view", "create", "update"],
  cashflow: ["view", "create"],
  reports: ["view"],
});

const productionOps = p({
  orders: ["view", "update"],
  inventory: ["view", "update"],
  production: ["view", "create", "update"],
  reports: ["view"],
});

const inventoryOps = p({
  inventory: ["view", "create", "update", "approve"],
  supplier: ["view", "create", "update"],
  production: ["view"],
  reports: ["view", "export"],
});

const viewerOps = p({
  "business-overview": ["view"],
  orders: ["view"],
  inventory: ["view"],
  production: ["view"],
  reports: ["view"],
  customers: ["view"],
});

export const jobRoleLibrary: JobRoleProfile[] = [
  // Restaurant
  {
    id: "restaurant-general-manager",
    sector: "restaurant",
    department: "Management",
    title: "Restaurant General Manager",
    aliases: ["Restaurant Manager", "Outlet Manager", "Store Manager"],
    baseRole: "MANAGER",
    seniority: "manager",
    description: "Runs daily restaurant operations, staffing, service quality, sales review, and operating discipline.",
    responsibilities: ["Review sales and daily reports", "Approve operational exceptions", "Coordinate front-of-house and kitchen", "Monitor shift performance"],
    recommendedPermissions: managerOps,
  },
  {
    id: "restaurant-shift-supervisor",
    sector: "restaurant",
    department: "Management",
    title: "Shift Supervisor",
    aliases: ["Shift Lead", "Floor Supervisor", "Duty Manager"],
    baseRole: "OPERATOR",
    seniority: "supervisor",
    description: "Controls one shift, handles exceptions, keeps service moving, and coordinates staff handoff.",
    responsibilities: ["Open or close shift", "Approve basic order changes", "Monitor queue and service floor", "Escalate stock or customer issues"],
    recommendedPermissions: p({ pos: ["view", "create", "update"], orders: ["view", "create", "update", "approve"], inventory: ["view"], production: ["view"], customers: ["view", "create"], reports: ["view"] }),
  },
  {
    id: "restaurant-cashier",
    sector: "restaurant",
    department: "Front of House",
    title: "Cashier / POS Operator",
    aliases: ["Checkout Operator", "Counter Staff", "Order Taker"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Handles customer checkout, payment, receipts, and order entry at POS.",
    responsibilities: ["Create customer orders", "Take payments", "Print receipts", "Sync order with kitchen/service flow"],
    recommendedPermissions: frontDeskOps,
  },
  {
    id: "restaurant-server",
    sector: "restaurant",
    department: "Front of House",
    title: "Server / Waiter",
    aliases: ["Waiter", "Waitress", "Service Crew", "Floor Staff"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Handles table service, customer requests, and order serving workflow.",
    responsibilities: ["View assigned orders", "Update served/completed status", "Handle table requests", "Communicate with kitchen"],
    recommendedPermissions: p({ orders: ["view", "update"], customers: ["view"], pos: ["view"] }),
  },
  {
    id: "restaurant-host",
    sector: "restaurant",
    department: "Front of House",
    title: "Host / Reservation Staff",
    aliases: ["Greeter", "Reservation Agent", "Front Desk"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Manages guest arrival, seating, reservations, and table flow.",
    responsibilities: ["View table state", "Seat customers", "Update waiting list", "Coordinate handoff to server"],
    recommendedPermissions: p({ pos: ["view"], orders: ["view"], customers: ["view", "create", "update"] }),
  },
  {
    id: "restaurant-head-chef",
    sector: "restaurant",
    department: "Kitchen",
    title: "Head Chef / Kitchen Manager",
    aliases: ["Chef de Cuisine", "Executive Chef", "Kitchen Lead"],
    baseRole: "MANAGER",
    seniority: "manager",
    description: "Leads kitchen production, recipe quality, prep control, and kitchen staff coordination.",
    responsibilities: ["Manage production queue", "Approve recipe or waste decisions", "Monitor stock usage", "Coordinate kitchen stations"],
    recommendedPermissions: p({ orders: ["view", "update", "approve"], inventory: ["view", "create", "update", "approve"], production: ["view", "create", "update", "approve"], reports: ["view"], supplier: ["view"] }),
  },
  {
    id: "restaurant-line-cook",
    sector: "restaurant",
    department: "Kitchen",
    title: "Line Cook / Cook",
    aliases: ["Cook", "Station Cook", "Chef de Partie", "Commis Cook"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Prepares menu items at a station and updates kitchen workflow progress.",
    responsibilities: ["View prep queue", "Start/finish production", "Report ingredient shortage", "Follow recipe procedure"],
    recommendedPermissions: productionOps,
  },
  {
    id: "restaurant-dishwasher",
    sector: "restaurant",
    department: "Kitchen Support",
    title: "Dishwasher / Kitchen Porter",
    aliases: ["Steward", "Plongeur", "Kitchen Assistant"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Supports kitchen cleanliness, dish flow, and basic prep support.",
    responsibilities: ["View assigned support tasks", "Mark cleaning task done", "Support kitchen station readiness"],
    recommendedPermissions: p({ production: ["view", "update"] }),
  },

  // Retail
  {
    id: "retail-store-manager",
    sector: "retail",
    department: "Management",
    title: "Retail Store Manager",
    aliases: ["Branch Manager", "Shop Manager", "Retail Manager"],
    baseRole: "MANAGER",
    seniority: "manager",
    description: "Runs store sales, inventory health, shift coverage, cash control, and store performance.",
    responsibilities: ["Review store KPIs", "Approve stock and pricing exceptions", "Manage staff access", "Review cashflow"],
    recommendedPermissions: managerOps,
  },
  {
    id: "retail-shift-lead",
    sector: "retail",
    department: "Management",
    title: "Retail Shift Lead",
    aliases: ["Supervisor", "Team Lead", "Duty Lead"],
    baseRole: "OPERATOR",
    seniority: "supervisor",
    description: "Supervises sales floor during a shift and handles basic operational overrides.",
    responsibilities: ["Monitor checkout lane", "Approve returns/exchanges", "Coordinate shelf replenishment", "Handle customer escalation"],
    recommendedPermissions: p({ pos: ["view", "create", "update", "approve"], orders: ["view", "create", "update"], inventory: ["view", "update"], customers: ["view", "create", "update"], reports: ["view"] }),
  },
  {
    id: "retail-cashier",
    sector: "retail",
    department: "Sales Floor",
    title: "Retail Cashier",
    aliases: ["Checkout Operator", "POS Associate", "Front-end Cashier"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Handles retail checkout, barcode scanning, payment, receipt, and simple returns.",
    responsibilities: ["Scan items", "Process payment", "Issue receipt", "Create return request"],
    recommendedPermissions: p({ pos: ["view", "create", "update"], orders: ["view", "create"], cashflow: ["view", "create"], customers: ["view", "create"] }),
  },
  {
    id: "retail-sales-associate",
    sector: "retail",
    department: "Sales Floor",
    title: "Sales Associate",
    aliases: ["Retail Associate", "Shop Assistant", "Customer Assistant"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Assists customers, checks product availability, and supports sales floor activity.",
    responsibilities: ["View products", "Assist customer inquiry", "Create sales order draft", "Update customer notes"],
    recommendedPermissions: p({ pos: ["view", "create"], inventory: ["view"], customers: ["view", "create"] }),
  },
  {
    id: "retail-stock-clerk",
    sector: "retail",
    department: "Inventory",
    title: "Stock Clerk / Shelf Replenishment",
    aliases: ["Stocker", "Merchandiser", "Shelf Staff"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Handles shelf restock, stock movement, shelf labels, and product placement.",
    responsibilities: ["View stock", "Update shelf movement", "Report low stock", "Assist stock opname"],
    recommendedPermissions: p({ inventory: ["view", "update"], supplier: ["view"], reports: ["view"] }),
  },
  {
    id: "retail-inventory-controller",
    sector: "retail",
    department: "Inventory",
    title: "Inventory Controller",
    aliases: ["Stock Controller", "Inventory Lead", "Stockroom Lead"],
    baseRole: "OPERATOR",
    seniority: "supervisor",
    description: "Controls retail stock accuracy, receiving, transfer, and adjustment workflow.",
    responsibilities: ["Approve adjustments", "Review stock movement", "Run stock opname", "Coordinate receiving"],
    recommendedPermissions: inventoryOps,
  },
  {
    id: "retail-buyer",
    sector: "retail",
    department: "Procurement",
    title: "Buyer / Purchasing Staff",
    aliases: ["Purchasing Officer", "Procurement Staff", "Category Buyer"],
    baseRole: "ADMIN",
    seniority: "operator",
    description: "Handles purchase planning, supplier coordination, and product replenishment.",
    responsibilities: ["Create purchase request", "Review supplier data", "Track receiving", "Coordinate reorder"],
    recommendedPermissions: p({ supplier: ["view", "create", "update", "approve"], inventory: ["view", "create", "update"], reports: ["view", "export"] }),
  },

  // Raw material / production / warehouse
  {
    id: "raw-material-operations-manager",
    sector: "raw-material",
    department: "Management",
    title: "Raw Material Operations Manager",
    aliases: ["Production Manager", "Warehouse Operations Manager", "Plant Operations Manager"],
    baseRole: "MANAGER",
    seniority: "manager",
    description: "Runs intake, weighing, storage, processing, quality gates, and raw material movement.",
    responsibilities: ["Approve raw material movement", "Review batch status", "Monitor shrinkage/waste", "Review supplier performance"],
    recommendedPermissions: managerOps,
  },
  {
    id: "raw-material-intake-operator",
    sector: "raw-material",
    department: "Receiving",
    title: "Intake / Receiving Operator",
    aliases: ["Receiving Clerk", "Goods Receiving Staff", "Inbound Operator"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Receives raw material from supplier, records intake, and starts traceability flow.",
    responsibilities: ["Create intake record", "Check supplier document", "Record condition", "Route item to weighing/storage"],
    recommendedPermissions: p({ inventory: ["view", "create", "update"], supplier: ["view", "create"], production: ["view"] }),
  },
  {
    id: "raw-material-weighing-operator",
    sector: "raw-material",
    department: "Weighing",
    title: "Weighing Operator",
    aliases: ["Scale Operator", "Weight Clerk", "Weighbridge Operator"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Records weight, validates variance, and connects intake to batch records.",
    responsibilities: ["Record gross/net weight", "Flag variance", "Update batch quantity", "Print/attach weighing label"],
    recommendedPermissions: p({ inventory: ["view", "update"], production: ["view", "update"], supplier: ["view"] }),
  },
  {
    id: "raw-material-quality-inspector",
    sector: "raw-material",
    department: "Quality Control",
    title: "Quality Control Inspector",
    aliases: ["QC Inspector", "Quality Technician", "Receiving Inspector"],
    baseRole: "OPERATOR",
    seniority: "supervisor",
    description: "Checks raw material quality, approves/rejects batches, and records quality notes.",
    responsibilities: ["Inspect material", "Approve/reject batch", "Create QC note", "Escalate failed quality gate"],
    recommendedPermissions: p({ inventory: ["view", "update", "approve"], production: ["view", "update", "approve"], reports: ["view", "export"] }),
  },
  {
    id: "raw-material-warehouse-staff",
    sector: "raw-material",
    department: "Warehouse",
    title: "Warehouse Staff",
    aliases: ["Warehouse Operator", "Material Handler", "Stockroom Staff"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Handles put-away, picking, movement, storage condition, and stock location.",
    responsibilities: ["Move material", "Update location", "Assist stock count", "Report damaged stock"],
    recommendedPermissions: p({ inventory: ["view", "update"], production: ["view"] }),
  },
  {
    id: "raw-material-production-operator",
    sector: "raw-material",
    department: "Processing",
    title: "Production / Processing Operator",
    aliases: ["Machine Operator", "Processing Staff", "Line Operator"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Runs processing step, updates batch progress, records output and waste.",
    responsibilities: ["Start processing", "Update batch progress", "Record output", "Record waste/shrinkage"],
    recommendedPermissions: productionOps,
  },
  {
    id: "raw-material-maintenance-technician",
    sector: "raw-material",
    department: "Maintenance",
    title: "Maintenance Technician",
    aliases: ["Equipment Technician", "Maintenance Worker", "Repair Technician"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Maintains equipment, handles repair tickets, and supports operational uptime.",
    responsibilities: ["View equipment issue", "Update repair task", "Record maintenance note", "Escalate downtime"],
    recommendedPermissions: p({ production: ["view", "update"], inventory: ["view"], reports: ["view"] }),
  },

  // Custom Business planned presets - deliberately broad service examples
  {
    id: "service-operations-manager",
    sector: "custom-business",
    department: "Management",
    title: "Service Operations Manager",
    aliases: ["Service Manager", "Branch Service Manager", "Operations Lead"],
    baseRole: "MANAGER",
    seniority: "manager",
    description: "Controls service delivery, staff scheduling, customer issue escalation, and service quality.",
    responsibilities: ["Review service tickets", "Approve refunds/adjustments", "Monitor SLA", "Manage team workload"],
    recommendedPermissions: managerOps,
  },
  {
    id: "service-front-desk",
    sector: "custom-business",
    department: "Front Desk",
    title: "Receptionist / Front Desk",
    aliases: ["Reception Staff", "Booking Desk", "Admin Front Office"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Handles bookings, customer intake, basic payment, and client communication.",
    responsibilities: ["Create customer profile", "Create booking/order", "Collect basic payment", "Update appointment status"],
    recommendedPermissions: frontDeskOps,
  },
  {
    id: "service-customer-service-rep",
    sector: "custom-business",
    department: "Customer Support",
    title: "Customer Service Representative",
    aliases: ["Support Agent", "Client Support", "Helpdesk Staff"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Responds to customer requests, updates service cases, and routes escalations.",
    responsibilities: ["View client history", "Create service ticket", "Update case note", "Escalate complaint"],
    recommendedPermissions: p({ customers: ["view", "create", "update"], orders: ["view", "create", "update"], reports: ["view"] }),
  },
  {
    id: "service-dispatcher",
    sector: "custom-business",
    department: "Scheduling",
    title: "Dispatcher / Scheduler",
    aliases: ["Service Scheduler", "Field Coordinator", "Booking Coordinator"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Assigns jobs to staff or field technicians and tracks schedule progress.",
    responsibilities: ["Assign job", "Update schedule", "Monitor job status", "Coordinate urgent cases"],
    recommendedPermissions: p({ orders: ["view", "create", "update", "approve"], customers: ["view", "update"], production: ["view", "update"], reports: ["view"] }),
  },
  {
    id: "service-field-technician",
    sector: "custom-business",
    department: "Field Service",
    title: "Field Service Technician",
    aliases: ["Technician", "Repair Technician", "Service Engineer"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Performs work orders on-site, updates job status, records parts/labor, and closes tasks.",
    responsibilities: ["View assigned jobs", "Update work order", "Record parts used", "Mark job complete"],
    recommendedPermissions: p({ orders: ["view", "update"], production: ["view", "update"], inventory: ["view", "update"], customers: ["view"] }),
  },
  {
    id: "service-cleaning-staff",
    sector: "custom-business",
    department: "Field Service",
    title: "Cleaning / Housekeeping Staff",
    aliases: ["Cleaner", "Housekeeper", "Janitorial Staff"],
    baseRole: "STAFF",
    seniority: "staff",
    description: "Handles assigned cleaning tasks, checklist completion, and service status update.",
    responsibilities: ["View assigned service task", "Update checklist", "Report issue", "Mark task complete"],
    recommendedPermissions: p({ orders: ["view", "update"], production: ["view", "update"], customers: ["view"] }),
  },
  {
    id: "service-maintenance-worker",
    sector: "custom-business",
    department: "Maintenance",
    title: "General Maintenance Worker",
    aliases: ["Handyman", "Maintenance Staff", "Facilities Technician"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Performs repair/maintenance work orders and updates task completion.",
    responsibilities: ["View work order", "Record action taken", "Request material", "Close maintenance job"],
    recommendedPermissions: p({ orders: ["view", "update"], production: ["view", "update"], inventory: ["view"], customers: ["view"] }),
  },
  {
    id: "service-consultant",
    sector: "custom-business",
    department: "Professional Service",
    title: "Consultant / Specialist",
    aliases: ["Service Consultant", "Advisor", "Specialist"],
    baseRole: "OPERATOR",
    seniority: "operator",
    description: "Delivers professional service, updates project/job milestones, and manages client notes.",
    responsibilities: ["View client data", "Update service milestone", "Create report note", "Request approval"],
    recommendedPermissions: p({ customers: ["view", "create", "update"], orders: ["view", "create", "update"], reports: ["view", "export"] }),
  },
  {
    id: "service-account-manager",
    sector: "custom-business",
    department: "Client Success",
    title: "Account Manager",
    aliases: ["Client Success Manager", "Relationship Manager", "Customer Success"],
    baseRole: "MANAGER",
    seniority: "manager",
    description: "Manages client relationships, renewals, escalations, and account health.",
    responsibilities: ["Review client profile", "Track account issues", "Approve client adjustment", "Review service history"],
    recommendedPermissions: p({ customers: ["view", "create", "update", "approve"], orders: ["view", "update", "approve"], reports: ["view", "export"], cashflow: ["view"] }),
  },
  {
    id: "service-billing-admin",
    sector: "custom-business",
    department: "Finance",
    title: "Billing / Invoice Admin",
    aliases: ["Billing Specialist", "Invoice Staff", "Payment Admin"],
    baseRole: "ADMIN",
    seniority: "operator",
    description: "Handles billing, invoices, payment reconciliation, and service charge review.",
    responsibilities: ["Create invoice", "Sync payment", "Review cashflow", "Export billing report"],
    recommendedPermissions: financeOps,
  },
];

export const sectorLabels: Record<BusinessRoleSector, string> = {
  restaurant: "Restaurant",
  retail: "Retail",
  "raw-material": "Raw Material / Production",
  "custom-business": "Custom Business (planned)",
};

export function getJobRoleById(id: string) {
  return jobRoleLibrary.find((role) => role.id === id) ?? jobRoleLibrary[0];
}

export function getJobRoleCountBySector(sector: BusinessRoleSector) {
  return jobRoleLibrary.filter((role) => role.sector === sector).length;
}
