import { Role } from "@prisma/client";

import { PERMISSIONS, type PermissionKey } from "./permissions";

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, PermissionKey[]> = {
  OWNER: Object.values(PERMISSIONS),

  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_UPDATE_STATUS,

    PERMISSIONS.MENU_VIEW,
    PERMISSIONS.MENU_CREATE,
    PERMISSIONS.MENU_UPDATE,
    PERMISSIONS.MENU_DELETE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_UPDATE,

    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_UPDATE,

    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_OPEN,
    PERMISSIONS.SHIFT_CLOSE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.ANALYTICS_VIEW,

    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,

    PERMISSIONS.SETTINGS_VIEW,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,
  ],

  CASHIER: [
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CANCEL,

    PERMISSIONS.TABLE_VIEW,

    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_OPEN,
    PERMISSIONS.SHIFT_CLOSE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CLOCK,

    PERMISSIONS.PAYMENT_VIEW,
  ],

  KITCHEN: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE_STATUS,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CLOCK,
  ],

  SERVER: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE_STATUS,

    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_UPDATE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CLOCK,
  ],
};